# Generated by Django 5.2.8 on 2025-11-26 15:37

import apps.app2.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_folder'),
        ('app2', '0009_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(default=apps.app2.models.default_due_date)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='reserved', max_length=20)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app2.bookbarcode')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app2.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.student')),
            ],
        ),
    ]
