# Generated by Django 5.2.8 on 2025-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
