# Generated by Django 5.2.8 on 2025-11-26 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_transaction_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_reserve',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
